const name = `const nameList = [Jaylee Barber
    Solomon Pineda
    Nola Graham
    Giovanni Herman
    Paulina Booth
    Chaim Lloyd
    Emely Love
    Jeffrey Vu
    Kimora Lester
    Lee Hogan
    Kathryn Cervantes
    Kamari Medrano
    Halle Blackburn
    Zahir Boyle
    Aliya Bradley
    Richard Ashley
    Khalani Palacios
    Thaddeus Acevedo
    Ashlynn Maldonado
    Javier Duffy
    Addisyn Craig
    Odin Guzman
    Ashley Drake
    Jalen Davenport
    Adrianna Huber
    Mac Schultz
    Briella Jefferson
    Raylan Hancock
    Katelyn Rivas
    Damon Baxter
    Lara Wilcox
    Jerry Pacheco
    Paris Villegas
    Clyde Deleon
    Gabrielle Donovan
    Brayan Mays
    Denisse Strong
    Axl Tang
    Belle Copeland
    Axton Camacho
    Armani Juarez
    Joaquin Novak
    Kaiya Peck
    Yousef Schaefer
    Mavis Rowe
    Kamden Brooks
    Autumn Miranda
    Rory Arnold
    Finley Hanna
    Aydin Galvan
    Dallas Prince
    Aron Delgado
    Alani Shields
    Devon Weaver
    Teagan Blankenship
    Ernesto Wise
    Mira Lee
    Jack Robinson
    Nora Salazar
    Brody Wyatt
    Liberty Murphy
    Cameron Waller
    Whitley Butler
    Ryder Blevins
    Aila Zavala
    Dillon McDowell
    Rayna Weber
    Crew Oliver
    Camille Briggs
    Case Weber
    Alayah Bailey
    Axel Wells
    Cecilia Woodard
    Westley James
    Quinn Wilson
    Daniel Chang
    Ophelia Gates
    Ermias Hall
    Leah Dickson
    Maxton Charles
    Jenna Rowland
    Eliezer Barry
    Waverly Orr
    Benicio Benjamin
    Jianna Clayton
    Boston Church
    Ayleen Patel
    Parker Dunlap
    Iliana Felix
    Rodney Buchanan
    Maryam Hester
    Rene Myers
    Lydia Welch
    Hendrix Warren
    Sloane Foley
    Mohammad Quintana
    Kenia Morse
    Bode Patel
    Madeline Weber
    Crew Patton
    Lorelei Baldwin
    Jaiden Bass
    Zahra Whitney
    Jeffery Schwartz
    Lilliana Kane
    Brock McPherson
    Emmaline Solomon
    Musa James
    Quinn Sanchez
    Joseph Gilbert
    Jocelyn Castro
    Jasper Glenn
    Blaire Hart
    Joel Guerrero
    Margot Leon
    Marshall Robles
    Felicity Richard
    Ahmed Wyatt
    Liberty Murillo
    Lance Sherman
    Addilyn Garza
    Judah Henson
    Kinslee Beck
    Eduardo Rangel
    Gloria Booth
    Chaim Shepherd
    Katalina Trevino
    Jaime Donovan
    Azariah Skinner
    Ridge Cardenas
    Raven Guerra
    Leland Medrano
    Halle Mayo
    Jericho Frazier
    Octavia Villarreal
    Nikolai Carrillo
    Kaylani Santiago
    Beckham Stephenson
    Khaleesi Wilcox
    Jerry Sutton
    Izabella Medrano
    Arian Robles
    Felicity Powers
    Sean Benson
    Collins Small
    Rudy Holmes
    Bailey Hester
    Rene O’Donnell
    Bellamy Richards
    Holden Baker
    Isla Bradford
    Ander Porter
    Ryleigh Clark
    John Nielsen
    Vienna Booker
    Dominik Burke
    Vera Gould
    Blaine Rowe
    Matilda Hodges
    Alonzo Walls
    Lilianna Peralta
    Dangelo Rosales
    Kinley Hanson
    Khalil Leach
    Martha Snow
    Houston Lindsey
    Colette Wyatt
    Sam Chung
    Rivka Chapman
    Knox Sharp
    Camryn Greer
    Koda Watkins
    Lola Benitez
    Justice Yang
    Angelina Huffman
    Chris Bradford
    Rhea Trujillo
    Apollo Hudson
    Kamila Eaton
    Leighton Bernal
    Emmeline Bradshaw
    Emory Sheppard
    Veda Clay
    Yosef Lara
    Heidi Arellano
    Kellan Contreras
    Daniela Burgess
    Kolton Ford
    Alexandra Hughes
    Everett Roman
    Astrid Cardenas
    Johnathan Williamson
    Catherine Meadows
    Wayne Keith
    Elyse Quinn
    Rhys Woods
    Reese Delacruz
    Memphis Keller
    Logan Santana
    Mohamed Garza
    River Salinas
    Edgar Sierra
    Marceline Best
    Harlem Esparza
    Ramona Marshall
    Kaiden Preston
    Indie Blanchard
    Adler Marquez
    Milani Olsen
    Skyler Cannon
    Noa Gardner
    Alan Carlson
    Kali Ortiz
    Landon Calderon
    Serena Gilbert
    Tobias Hayden
    Avayah Duke
    Kalel Reese
    Rosemary Kelley
    Eric Strickland
    Nia Wilson
    Daniel Hogan
    Kathryn Cole
    Nathaniel Delgado
    Alani Mahoney
    Kamryn Bush
    Everlee Evans
    Elias Hoover
    Virginia Hernandez
    Mason Whitaker
    Ivanna Stephens
    Messiah Benjamin
    Jianna Mathis
    Gustavo Nguyen
    Nova Garcia
    James Camacho
    Armani Webb
    Lorenzo Lang
    Amirah Ellis
    Cole Rangel
    Gloria Cano
    Terry Charles
    Jenna Moran
    Tate Madden
    Violette Schaefer
    Ishaan Howard
    Sophie Beard
    Nathanael Whitaker
    Ivanna Garza
    Judah Houston
    Lylah Townsend
    Alexis Ali
    Zelda Clarke
    Stetson Williams
    Ava Cortez
    Zayn Cohen
    Destiny Cherry
    Rome Beard
    Ezra Malone
    Ruben Frazier
    Octavia Fernandez
    Bentley Everett
    Noah Espinoza
    Dallas Salas
    Amber Woodward
    Jeremias Garcia
    Amelia Stout
    Callahan Peterson
    Caroline Perkins
    Kyrie Beck
    Gia McCall
    Kiaan Ali
    Zelda Pope
    Gunnar Wheeler
    Sydney Frazier
    Callum Holloway
    Mae Turner
    Joshua Dean
    Julianna Vu
    Kamdyn Nielsen
    Vienna Boyer
    Zeke David
    Haylee McCoy
    Jett Walter
    Penny Hurst
    Neil Young
    Zoey Dickerson
    Flynn Walton
    Scarlet Rivera
    Charles Burns
    Emerson Todd
    Baylor Bradford
    Rhea Snow
    Houston O’Connor
    Charli Buckley
    Aryan Alvarado
    Blake McCullough
    Briar Gordon
    Taylor Hunter
    Archer Fry
    Clarissa Bender
    Zavier Shaffer
    Alanna Thompson
    Theodore Davila
    Rayne Hawkins
    Victor Pierce
    Arabella Orr
    Benicio Sullivan
    Melanie Rodgers
    Mathias Barber
    Cassidy Lowe
    Julius Duffy
    Addisyn Griffin
    Ayden Blackburn
    Frida Nicholson
    Rodrigo Kaur
    Holland Aguirre
    Andy Santiago
    Nyla Wise
    Frederick Medrano
    Halle Doyle
    Kashton Atkinson
    Jazmin Ferguson
    Miguel Dougherty
    Alisson Valdez
    Kyler Dunlap
    Iliana Mills
    Alex Lowery
    Estelle Potts
    Alfred Meyers
    Leyla Decker
    Taylor Thornton
    Haisley Hardin
    Hassan Parrish
    Tiana Reid
    Josue Rivers
    Kiana Woodward
    Jeremias Holland
    Mariah Trujillo
    Apollo Horn
    Avah Sanchez
    Joseph Greer
    Reina Tucker
    Ivan Zavala
    Liv Berg
    Cayson Waller
    Whitley Holloway
    Sutton Mendez
    Londyn Anderson
    Jacob Friedman
    Aspyn Anderson
    Jacob Bean
    Jenesis Ramos
    Angel Macdonald
    Rosalia Horton
    Garrett Merritt
    Kaisley Duarte
    Abdullah Marshall
    Adalyn Roach
    Caspian Swanson
    Helen Greene
    Griffin Person
    Dylan Ray
    Arlo Spencer
    Alyssa Lewis
    Wyatt Baldwin
    Esmeralda Clements
    Fisher Lara
    Heidi Maynard
    Landry Blackwell
    Saoirse Arellano
    Kellan Pearson
    Kiara Baldwin
    Jaiden Anthony
    Macy Greer
    Koda Pollard
    Marisol Beck
    Eduardo Brandt
    Loretta Atkinson
    Duke Bruce
    Marilyn Brooks
    Jordan Walls
    Lilianna Andersen
    Alistair Newton
    Braelynn McCormick
    Jasiah O’Connell
    Jillian Costa
    Kenji Chandler
    Viviana Thornton
    Malik Reid
    Charlee McFarland
    Dane Prince
    Greta Herring
    Henrik Crane
    Della Esparza
    Carl Poole
    Bonnie Chang
    Ari Lang
    Amirah Gregory
    Travis Anthony
    Macy Macias
    Moshe Robinson
    Nora Curry
    Briggs Church
    Ayleen Holloway
    Sutton Price
    Piper Mahoney
    Kamryn Bass
    Zahra McGee
    Conner Bailey
    Kennedy Simon
    Zayne Henson
    Kinslee Duke
    Kalel Lozano
    Cecelia Villegas
    Clyde Nash
    Novah Thompson
    Theodore Archer
    Kadence Trejo
    Wesson Burke
    Vera Wilson
    Daniel Callahan
    Kimber Sellers
    Madden Marsh
    Adelina Velasquez
    Sullivan Mendez
    Londyn Wright
    Grayson Cooper
    Serenity Ventura
    Branson Willis
    Alexa Perez
    Owen Morton
    Mallory Bonilla
    Aden Patterson
    Kaylee Hurst
    Neil Bates
    Madilyn Moreno
    Myles Savage
    Louise Cole
    Nathaniel Cole
    Margaret McGuire
    Casey Andrews
    Payton Morrow
    Kyree Molina
    Alexandria Correa
    Zakai Singh
    Vivienne Blevins
    Avi Johnson
    Emma Owens
    Adriel Rhodes
    Tatum Adkins
    Kylo Villegas
    Jessie Hensley
    Layne Horton
    Aitana Williams
    Oliver Perez
    Eleanor Clark
    John Macias
    Adley Weber
    Crew Mosley
    Zaniyah Harper
    Hayes Maxwell
    Kyla Short
    Hezekiah Ramirez
    Grace Pierce
    Nicolas Wood
    Natalia Espinosa
    Khalid Gray
    Sarah Ventura
    Branson Roberson
    Sasha Magana
    Rey Chavez
    Nevaeh Williams
    Oliver Ahmed
    Jolie Burke
    Jax Ingram
    Katie Gallegos
    Jonas Shelton
    Makenzie Chen
    Emmanuel Marshall
    Adalyn McMahon
    Jakob Howard
    Sophie Payne
    Edward Ashley
    Khalani Savage
    Keaton Singleton
    Malaysia Bishop
    Paxton Giles
    Bailee Truong
    Ayan Schneider
    Delaney Jackson
    Sebastian Hoffman
    Aspen Russo
    Jamie Potts
    Ellison Rodriguez
    Henry Webster
    Kensley Mullins
    Allen Reilly
    Tori Ortiz
    Landon Melendez
    Bethany McLaughlin
    Ibrahim Jaramillo
    Guadalupe James
    Jaxson Valenzuela
    Henley Koch
    Salvador Liu
    Kate Manning
    Seth May
    Adriana Walsh
    Bodhi Hall
    Leah Briggs
    Case Freeman
    Norah Richards
    Holden Manning
    Jennifer Duke
    Kalel Robertson
    Harmony Nava
    Stefan Kent
    Jazmine Jensen
    Cash Holland
    Mariah Hughes
    Everett Silva
    Lucia Boyd
    Dean Knapp
    Linda Robinson
    Matthew Roach
    Lyanna Orozco
    Keanu Wagner
    Maeve Esparza
    Carl Moran
    Celeste Washington
    Juan O’Donnell
    Bellamy Fernandez
    Bentley Andrade
    Emmy Delarosa
    Osiris Gibson
    Eden James
    Jaxson Anthony
    Macy Zimmerman
    Sergio Crosby
    Keily Medina
    George Matthews
    Lila Wilkerson
    Carmelo Cano
    Egypt Correa
    Zakai Miles
    Alessandra Macdonald
    Hugh Person
    Dylan Atkins
    Cason Wilkerson
    Janiyah Lambert
    Mario Monroe
    Carly Ballard
    Kenzo Alfaro
    Yasmin Freeman
    Jayce Vazquez
    Journee O’Neill
    Marcel Fox
    Juliette Person
    Moses Pierce
    Arabella Montes
    Darren Duarte
    Kynlee Paul
    Noel Cline
    Lina Mendoza
    Dominic Fuller
    Oakley Murray
    Ashton Enriquez
    Nellie Williams
    Oliver Weaver
    Teagan Ochoa
    Winston Norton
    Kylee Sparks
    Drake Ventura
    Zora Morris
    Christian Choi
    Karla Hughes
    Everett Mullen
    Shay Rice
    Graham Duncan
    Elise Byrd
    Cristian Ali
    Zelda Stanton
    Zyair Ochoa
    Luciana Marks
    Amos Doyle
    Annalise Palacios
    Thaddeus Huynh
    Oaklee Malone
    Ruben Hampton
    Leona Henderson
    Beau Bennett
    Josephine Garrison
    Noe Kelley
    Rosalie Fox
    Antonio Alfaro
    Yasmin Browning
    Rohan Spears
    Isabela Boone
    Mauricio Bond
    Alena Summers
    Darius Charles
    Jenna Bass
    Landen Hendrix
    Zhuri Snyder
    Thiago Snyder
    Callie Willis
    Remington Cameron
    Julie Parra
    Davion Barnett
    Harlow Potter
    Lucca Carey
    Alora Marks
    Amos Potter
    Rory Dougherty
    Brett Gibbs
    Carter Love
    Jeffrey Cannon
    Noa Cisneros
    Alden Richard
    Davina McDowell
    Lachlan Li
    Paige Morgan
    Hunter Davila
    Rayne Cooper
    Jonathan Sanders
    Everleigh McCarthy
    Devin Conner
    Alondra Rowland
    Eliezer Duke
    Melani Lane
    Matias Bernard
    Barbara Norris
    Cairo Anderson
    Ella Zhang
    Isaias Strickland
    Nia McCormick
    Jasiah Ramos
    Alice Burns
    August Cannon
    Noa Lynch
    Zane Shelton
    Makenzie Fernandez
    Bentley Diaz
    Elena Rosas
    Remi Reyes
    Audrey Sheppard
    Trent Daniel
    Joy Mercado
    Abram Weber
    Alayah Black
    Matteo Gibson
    Eden Davenport
    Dariel Salazar
    Freya Diaz
    Nathan McMahon
    Belen Vega
    Aidan Blake
    Amanda Acosta
    Jensen Castro
    Eloise Cantu
    Anakin Kemp
    Anika Pham
    Russell Patrick
    Lyra Miller
    Benjamin McCann
    Joyce Cox
    Connor Sparks
    Aisha Tanner
    Bruno Caldwell
    Evelynn Randolph
    Eugene Graves
    Elle Blackburn
    Zahir Reyes
    Audrey McDowell
    Lachlan Schmidt
    Kimberly Cole
    Nathaniel Gentry
    Amelie Collier
    Edison Reyes
    Audrey Salinas
    Edgar Nichols
    Aliyah Hayes
    Legend Berger
    Laylah Valdez
    Kyler Henson
    Kinslee Hunt
    Jesus Heath
    Amani Abbott
    Kohen Carey
    Alora Hubbard
    Forrest Eaton
    Miley Phan
    Maison Stein
    Leilany Coleman
    Micah Cross
    Nayeli Buck
    Jon Mejia
    Saylor Jones
    William Harrington
    Legacy Webb
    Lorenzo Sparks
    Aisha Hughes
    Everett Contreras
    Daniela Andersen
    Alistair Reid
    Charlee McClain
    Mitchell Bridges
    Elora Ellison
    Kye Bennett
    Josephine Barr
    Harley Casey
    Sylvia Blanchard
    Adler Koch
    Milana Cameron
    Rayan Knox
    Kallie Sandoval
    Brantley Hicks
    Alina Holmes
    King David
    Haylee Gentry
    Magnus Maldonado
    Elaina Mullins
    Allen Fuentes
    Madeleine Pitts
    Trey Vasquez
    Rose Lang
    Wells Person
    Dylan Roy
    Marcelo Medrano
    Halle Silva
    Luka Kelly
    Ruby Montoya
    Ford Hammond
    Holly Meyers
    Julien Dillon
    Laurel Case
    Bentlee Montoya
    Kamryn Fleming
    Fernando Fitzgerald
    Marlee Savage
    Keaton Mills
    June Case
    Bentlee Stevens
    Katherine Heath
    Lionel Norman
    Malani Huff
    Finnley Ruiz
    Emery Hayes
    Legend Hicks
    Alina Blankenship
    Ernesto Harrington
    Legacy Delacruz
    Memphis Nunez
    Mya Marshall
    Kaiden Parra
    Dalary Rangel
    Saint Jarvis
    Elisabeth Maldonado
    Javier Faulkner
    Ansley Rosas
    Remi Page
    Cataleya Yates
    Braylon Lawrence
    Lauren Beasley
    Stanley Mercado
    Mckinley Chapman
    Knox Barr
    Noemi Evans
    Elias Hester
    Zendaya Case
    Bentlee Booth
    Zariyah Bartlett
    Kace Owens
    Amaya Rodgers
    Mathias Ventura
    Zora Cain
    Benson Tanner
    Harmoni Fry
    Jacoby Stone
    Catalina Ryan
    Timothy Baldwin
    Esmeralda Mathews
    Jamir Griffin
    Charlie Lloyd
    Zaire Mason
    Sienna Holmes
    King Sutton
    Izabella Raymond
    Maurice Shepherd
    Katalina Gallagher
    Marcos Olsen
    Oaklyn Herman
    Juelz Pollard
    Marisol Best
    Harlem Hobbs
    Lacey Wiley
    Mathew Pugh
    Landry Cano
    Terry Flynn
    Dorothy Allison
    Dennis Ortiz
    Anna Fowler
    Kameron Johnson
    Emma Nava
    Stefan Chambers
    Makayla Wallace
    Chase Dalton
    Lilian Patterson
    Amir Trevino
    Priscilla Mills
    Alex Pugh
    Landry Gibson
    Tyler Parker
    Aubrey Kirby
    Tony Sweeney
    Yara Hubbard
    Forrest Quintero
    Keyla Salgado
    Trace Prince
    Greta Reese
    Alijah Decker
    Aleena Dixon
    Camden Montoya
    Kamryn Esparza
    Carl Neal
    Talia Moore
    Levi Sanchez
    Aria Nolan
    Maximo Wiggins
    Capri O’Connell
    Jovanni Landry
    Brynleigh Robles
    Otto Douglas
    Aniyah Khan
    Kendrick Rojas
    Adaline Hood
    Brixton Gilbert
    Jocelyn Gates
    Ermias Haynes
    Lexi Swanson
    Hugo Marsh
    Adelina Wilcox
    Jerry Mayer
    Ainhoa Stevens
    Zachary Fox
    Juliette Nicholson
    Rodrigo Baker
    Isla Raymond
    Maurice Spence
    Aislinn Small
    Rudy Lugo
    Kaylie Rowe
    Kamden Estes
    Brittany Huerta
    Douglas Berg
    Emmalyn Moses
    Niklaus Henderson
    Maria George
    Mark Casey
    Sylvia Cannon
    Archie Francis
    Daniella Yang
    Malcolm Malone
    Skyler Zimmerman
    Sergio Wyatt
    Liberty Pitts
    Trey Barajas
    Keilani Delarosa
    Osiris Pearson
    Kiara McMahon
    Jakob Blevins
    Aila Ventura
    Branson Mendez
    Londyn Rowland
    Eliezer Park
    Lia Hull
    Salem Small
    Zaria Ortega
    Kobe Mercado
    Mckinley Mathews
    Jamir Jimenez
    Adeline Harrison
    Gavin Middleton
    Madalyn Fry
    Jacoby McDaniel
    Dahlia Cervantes
    Kamari Shah
    Angelica Garrison
    Noe Aguilar
    Josie Bean
    Mccoy Ahmed
    Jolie Moyer
    Ahmir Page
    Cataleya Campbell
    Christopher Molina
    Alexandria Thornton
    Malik Lozano
    Cecelia Keith
    Jagger Vu
    Kimora Smith
    Liam Carrillo
    Kaylani Steele
    Elian Bond
    Alena Warren
    Abel Lyons
    Kenzie Sellers
    Madden Bryant
    Parker Villegas
    Clyde Jarvis
    Elisabeth Nash
    Chandler Santiago
    Nyla Wyatt
    Sam Castaneda
    Keira Gutierrez
    Luca Arias
    Aleah Wheeler
    Kenneth Neal
    Talia Ferguson
    Miguel Meyer
    Sara Holt
    Niko Arroyo
    Kyra Bailey
    Axel Anderson
    Ella Franco
    Gage Byrd
    Giselle Schmitt
    Murphy Wilkins
    Amalia Andersen
    Alistair Ferguson
    Juliana Stark
    Kristopher Young
    Zoey Morris
    Christian Ponce
    Aileen Lamb
    Kaysen Gilbert
    Jocelyn Wang
    Cohen Salazar
    Freya Rosales
    Wilder Potts
    Ellison Strong
    Axl Boyle
    Aliya Cain
    Benson Meadows
    Pearl Espinoza
    Dallas Orozco
    Renata Cabrera
    Cade Garza
    River Archer
    Ephraim Raymond
    Hadlee Stafford
    Alfredo Parks
    Ainsley Moran
    Tate Valenzuela
    Henley Frost
    Dario Jensen
    Jane Franklin
    Simon Moran
    Celeste Wright
    Grayson Holland
    Mariah Landry
    Jaxx Hicks
    Alina Zavala
    Dillon Haley
    Addilynn Meyer
    Tristan Kelly
    Ruby McIntosh
    Kristian Dixon
    Blakely Fuentes
    Bowen House
    Sariah Stein
    Creed Franco
    Charleigh Mathews
    Jamir Estes
    Brittany Dunn
    Dawson Raymond
    Hadlee Rush
    Kaiser Berger
    Laylah Knight
    Beckett Rich
    Sunny Knox
    Valentin Chase
    Angie Bond
    Roger Hartman
    Kennedi Bass
    Landen Hester
    Zendaya Walton
    Dominick O’Connor
    Charli Coleman
    Micah Bell
    Melody Mathis
    Gustavo Dominguez
    Raegan Tanner
    Bruno Rose
    Magnolia McLaughlin
    Ibrahim Michael
    Aubriella Rasmussen
    Will Reyna
    Luella Vargas
    Ryker Gordon]`;
// write to json file
const nameListArray = name.split("\n").map((name, index) => {
	return name
		.trim()
		.replace(/[\[\]']+/g, "")
		.replace(/,/g, "");
});
const fs = require("fs");
const jsonData = JSON.stringify(nameListArray, null, 2);
fs.writeFileSync("nameList.json", jsonData, "utf8", (err) => {
	if (err) {
		console.error("Error writing to file", err);
	} else {
		console.log("JSON data is saved.");
	}
});
