const players_data = [
    {
        id: 1,
        name: "John Doe",
        image: "",
        eloRating: 1500,
    },
    {
        id: 2,
        name: "Jane Smith",
        image: "",
        eloRating: 1450,
    },
    {
        id: 3,
        name: "Alice Johnson",
        image: "",
        eloRating: 1600,
    },
    {
        id: 4,
        name: "Bob Brown",
        image: "",
        eloRating: 1550,
    },
    {
        id: 1,
        name: "John Doe",
        image: "",
        eloRating: 1500,
    },
    {
        id: 2,
        name: "Jane Smith",
        image: "",
        eloRating: 1450,
    },
    {
        id: 3,
        name: "Alice Johnson",
        image: "",
        eloRating: 1600,
    },
    {
        id: 4,
        name: "Bob Brown",
        image: "",
        eloRating: 1550,
    }, {
        id: 1,
        name: "John Doe",
        image: "",
        eloRating: 1500,
    },
    {
        id: 2,
        name: "Jane Smith",
        image: "",
        eloRating: 1450,
    },
    {
        id: 3,
        name: "Alice Johnson",
        image: "",
        eloRating: 1600,
    },
    {
        id: 4,
        name: "Bob Brown",
        image: "",
        eloRating: 1550,
    }, {
        id: 1,
        name: "John Doe",
        image: "",
        eloRating: 1500,
    },
    {
        id: 2,
        name: "Jane Smith",
        image: "",
        eloRating: 1450,
    },
    {
        id: 3,
        name: "Alice Johnson",
        image: "",
        eloRating: 1600,
    },
    {
        id: 4,
        name: "Bob Brown",
        image: "",
        eloRating: 1550,
    }, {
        id: 1,
        name: "John Doe",
        image: "",
        eloRating: 1500,
    },
    {
        id: 2,
        name: "Jane Smith",
        image: "",
        eloRating: 1450,
    },
    {
        id: 3,
        name: "Alice Johnson",
        image: "",
        eloRating: 1600,
    },
    {
        id: 4,
        name: "Bob Brown",
        image: "",
        eloRating: 1550,
    }, {
        id: 1,
        name: "John Doe",
        image: "",
        eloRating: 1500,
    },
    {
        id: 2,
        name: "Jane Smith",
        image: "",
        eloRating: 1450,
    },
    {
        id: 3,
        name: "Alice Johnson",
        image: "",
        eloRating: 1600,
    },
    {
        id: 4,
        name: "Bob Brown",
        image: "",
        eloRating: 1550,
    }, {
        id: 1,
        name: "John Doe",
        image: "",
        eloRating: 1500,
    },
    {
        id: 2,
        name: "Jane Smith",
        image: "",
        eloRating: 1450,
    },
    {
        id: 3,
        name: "Alice Johnson",
        image: "",
        eloRating: 1600,
    },
    {
        id: 4,
        name: "Bob Brown",
        image: "",
        eloRating: 1550,
    }, {
        id: 1,
        name: "John Doe",
        image: "",
        eloRating: 1500,
    },
    {
        id: 2,
        name: "Jane Smith",
        image: "",
        eloRating: 1450,
    },
    {
        id: 3,
        name: "Alice Johnson",
        image: "",
        eloRating: 1600,
    },
    {
        id: 4,
        name: "Bob Brown",
        image: "",
        eloRating: 1550,
    },
    {
        id: 5,
        name: "Charlie Davis",
        image: "",
        eloRating: 1400,
    },
    {
        id: 6,
        name: "Diana Evans",
        image: "",
        eloRating: 1650,
    },
    {
        id: 7,
        name: "Ethan Wilson",
        image: "",
        eloRating: 1350,
    },
    {
        id: 8,
        name: "Fiona White",
        image: "",
        eloRating: 1700,
    },
    {
        id: 9,
        name: "George Harris",
        image: "",
        eloRating: 1300,
    },
    {
        id: 10,
        name: "Hannah Clark",
        image: "",
        eloRating: 1750,
    },
];

export default players_data;